http:
  port: 8080
grpc:
  port: 8081
logger:
  logLevel: "info"
  logFormat: "json"
db:
  driver: "postgres"
  name: "postgres"
  host: "db_postgres"
  port: 5432
  user: "postgres"
  password: "mysecretpassword"
  sslmode: "disable"
  dbName: "postgres"
  maxIdleConns: 10
  maxOpenConns: 5
