services:
  db_postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  app_http:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      db_postgres:
#        condition: service_healthy
#    entrypoint: [ "/app/app", "http", "--config", "/app/config.yaml" ]
#
#  app_grpc:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      db_postgres:
#        condition: service_healthy
#    entrypoint: [ "/app/app", "grpc", "--config", "/app/config.yaml" ]

volumes:
  db_data:
